/* !!! WARNING: This is a GENERATED Code..Please do NOT Edit !!! */

std::map<std::string, std::set<LedManager::LedAction>> LedManager::gMap = {

	{"FanA2Identify",{
		{"Fan_A2",BLINK},
		{"EnclosureIdentifyFront",ON},
		{"EnclosureIdentifyBack",ON},
	}},
	{"FanA2Fault",{
		{"Fan_A2",ON},
		{"EnclosureFaultBack",ON},
		{"EnclosureFaultFront",ON},
	}},
	{"EnclosureIdentify",{
		{"EnclosureIdentifyFront",BLINK},
		{"EnclosureIdentifyBack",BLINK},
	}},
	{"FanA3Identify",{
		{"Fan_A3",BLINK},
		{"EnclosureIdentifyFront",ON},
		{"EnclosureIdentifyBack",ON},
	}},
	{"FanA4Fault",{
		{"EnclosureFaultBack",ON},
		{"EnclosureFaultFront",ON},
		{"Fan_A4",ON},
	}},
	{"FanA1Fault",{
		{"Fan_A1",ON},
		{"EnclosureFaultBack",ON},
		{"EnclosureFaultFront",ON},
	}},
	{"PowerOff",{
		{"PanelPowerButtonNote1",BLINK},
		{"OpPanelFront",BLINK},
	}},
	{"PowerSupply1Identify",{
		{"PowerSupply_1",BLINK},
		{"EnclosureIdentifyFront",ON},
		{"EnclosureIdentifyBack",ON},
	}},
	{"PowerSupply1Fault",{
		{"PowerSupply_1",ON},
		{"EnclosureFaultBack",ON},
		{"EnclosureFaultFront",ON},
	}},
	{"FanA4Identify",{
		{"EnclosureIdentifyFront",ON},
		{"EnclosureIdentifyBack",ON},
		{"Fan_A4",BLINK},
	}},
	{"PowerOn",{
		{"PanelPowerButtonNote1",ON},
		{"OpPanelFront",ON},
	}},
	{"FanA1Identify",{
		{"Fan_A1",BLINK},
		{"EnclosureIdentifyFront",ON},
		{"EnclosureIdentifyBack",ON},
	}},
	{"PowerSupply2Identify",{
		{"PowerSupply_2",BLINK},
		{"EnclosureIdentifyFront",ON},
		{"EnclosureIdentifyBack",ON},
	}},
	{"EnclosureFault",{
		{"EnclosureFaultBack",ON},
		{"EnclosureFaultFront",ON},
	}},
	{"FanA3Fault",{
		{"Fan_A3",ON},
		{"EnclosureFaultBack",ON},
		{"EnclosureFaultFront",ON},
	}},
	{"PowerSupply2Fault",{
		{"PowerSupply_2",ON},
		{"EnclosureFaultBack",ON},
		{"EnclosureFaultFront",ON},
	}},
};
